### PR TITLE
Feature/tf client

### PR DESCRIPTION
**Pull request by rbonghi**
Added tfClient functionality.

Now the Navigator can read robot position from tfClient.

Added option to change name for **robot topic**

### CODE REVIEW

**Comment by rctoris** [comment]
Looks like a merge conflict/build fail on this one.

**Comment by rbonghi** [comment]
Ok, I've lost a semicolon :)

**Comment by rbonghi** [comment]
Sorry I've accidentally closed this branch.

**Comment by rctoris** [comment]
Still have a merge conflict on this one :)

**Pull request merged**
